export const PRODUCTS = {
    FETCH: 'PRODUCTS_FETCH',
    FETCH_ERROR: 'PRODUCTS_FETCH_ERROR',
    FETCH_SUCCESS: 'PRODUCTS_FETCH_SUCCESS',
    FETCH_ID_SUCCESS: 'PRODUCTS_FETCH_ID_SUCCESS'
}

export const ACCOUNT = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS'
}

export const FAVORITES = {
    FETCH: 'FAVORITES_FETCH',
    FETCH_ERROR: 'FAVORITES_FETCH_ERROR',
    FETCH_SUCCESS: 'FAVORITES_FETCH_SUCCESS',
    FETCH_FAV_SUCCESS: 'FAVORITES_FETCH_FAV_SUCCESS'
}

